__title__ = "FastSearch"
__description__ = "Price tracking and comparison tool for online shopping"
__url__ = "https://github.com/rasadov/fastsearch"
__author__ = "Rauf Asadov"
__author_email__ = "raufasadov23@gmail.com"
__license__ = "MIT"
__copyright__ = "(c) 2024 by Rauf Asadov"
